

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Load Packages
library(geodata)
library(terra)
library(dplyr)
library(tidyr)
library(sf)
library(ggplot2)
library(rnaturalearth)
library(readr)
library(lubridate)
library(arrow)
library(DT)
library(tidyterra)
```

```{r echo=TRUE}
SRDB_Data <- read.csv("srdb-data.csv")

```

```{r echo=FALSE}
# Longitude and Latitude isolated
SRDB_Data |>
  as_tibble() |>
  select(Longitude, Latitude, MAT, Rs_annual, Record_number, MAP) |>
  filter(!is.na(Longitude), !is.na(Latitude)) ->
  SRDB_filtered
```

```{r echo=FALSE}
coords <- SRDB_filtered %>% select(Longitude, Latitude)
print(SRDB_Data)
# Start simple and small, with 10 degree resolutions (smallest data)
temp_data <- worldclim_global(var = "tavg", res = 10, path = "raw_data/worldclim_data/")
temp_values <- terra::extract(temp_data, coords)
print(temp_values)
```

```{r echo=FALSE, warning=FALSE}
# Mean of MAT
SRDB_filtered$MAT_wc <- rowMeans(temp_values[, -1], na.rm = TRUE)
head(SRDB_filtered)


# Acid test: plot MAT versus MAT_worldclim
ggplot(data = SRDB_filtered, aes(x = MAT, y = MAT_wc, color = Latitude))+
  geom_point(size = 2)+
  geom_abline() 
```

```{r echo=FALSE, warning=FALSE}
# World Clim data on world map
world_coords <- map_data("world")
world <- ne_countries()
ggplot(world)+
  geom_sf()+
  geom_point(data = SRDB_filtered, aes(x=Longitude, y=Latitude, colour = MAT_wc), size = 1)+
  scale_color_viridis_c()
```

```{r echo=TRUE}
# Precip Data
prec_data <- worldclim_global(var = "prec", res = 10, path = "raw_data/worldclim_data/")
prec_values <- terra::extract(prec_data, coords)
# Monthly val converted to mm
SRDB_filtered$MAP_wc <- rowSums(temp_values[, -1], na.rm = TRUE)*10
print(prec_values)
head(SRDB_filtered)
```

```{r echo=FALSE, warning=FALSE}
# MAP v MAP_wc plotted
ggplot(data = SRDB_filtered, aes(x = MAP, y = MAP_wc, color = Latitude))+
  geom_point(size = 2)+
  geom_abline()

world_coords <- map_data("world")
world <- ne_countries()
ggplot(world)+
geom_sf()+
  geom_point(data = SRDB_filtered, aes(x=Longitude, y=Latitude, colour = MAP_wc), size = 1)+
  scale_color_viridis_c()
  
head(world_coords)
```

```{r echo=FALSE, warning=FALSE}
# Reading in Permafrost Data
permafrost_map <- terra::rast("raw_data/NCSCDv2_Circumpolar_raster_1deg/NCSCDv2_Circumpolar_raster_1deg/NCSCDv2_Circumpolar_WGS84_pfregion_extent_1deg.tif")
plot(permafrost_map)
```

```{r echo=FALSE, warning=FALSE}
# Plotting SRDB on Permafrost map
ggplot()+
  geom_spatraster(data = permafrost_map, aes(fill = OID))+
geom_point(data = SRDB_filtered, aes(x = Longitude, y = Latitude, colour = Rs_annual), size = 2)
```

```{r echo=FALSE, warning=FALSE}
# Reading in gelisol data
gelisol <- terra::rast("raw_data/NCSCDv2_Circumpolar_raster_1deg/NCSCDv2_Circumpolar_raster_1deg/NCSCDv2_Circumpolar_WGS84_gelisol_pct_1deg.tif")
SRDB_points <- vect(SRDB_filtered, geom = c("Longitude", "Latitude"), crs = crs(gelisol))
gelisol_extract <- terra::extract(gelisol, SRDB_points)
SRDB_filtered$gelisol <- as.numeric(gelisol_extract[ , 2])/100
gelisol_filtered <- SRDB_filtered[!is.na(SRDB_filtered$gelisol), ]
```

```{r echo=FALSE, warning=FALSE}
ggplot(world)+
  geom_sf()+
geom_point(data = SRDB_filtered, aes(x = Longitude, y = Latitude, colour = gelisol), size = 1)+
  scale_color_viridis_c()
```
```{r echo=FALSE}
mod <- lm(formula = Rs_annual~MAT_wc+SRDB_filtered$gelisol, data = SRDB_filtered)
summary(mod)
plot(mod)
```
